### ISSUE TITLE
[Bug] variable interpolation not working

### ISSUE THREAD

**Issue by SwiftWinds** [Thream/styled-jsx-plugin-sass#101]
## Steps To Reproduce

1. Install plugin and setup .babelrc.json
2. Interpolate a const variable into the styled-jsx SCSS codeblock
3. Observe the style not being applied

## Minimal example

https://stackblitz.com/edit/nextjs-1uw1yf?file=pages/index.js

**Comment by Divlo** [comment]
Hey! :wave:

Thanks for your report! @SwiftWinds 
I guess that's more a `styled-jsx` than an issue with this plugin, as, without this plugin, it still doesn't work, maybe worth opening an issue on [vercel/styled-jsx](https://github.com/vercel/styled-jsx) repo.

**Comment by SwiftWinds** [comment]
Hmm... OK. I'm looking at `index.js` and struggling to understand what's going on. I'll perhaps get some sleep and come back tomorrow to take a fresh look. In the meantime, got any suitable workarounds?

**Comment by SwiftWinds** [comment]
How am I supposed to turn a plain JavaScript variable into a SASS variable though? I need to use the constant in places besides SASS.

**Comment by belkosyak** [comment]
in 4.0.2 same problem with interpolation still exists when generating className using `css.resolve` and trying to use `${someVar}` for root element styles, so in regular SASS terms it would be

```
const { className, styles } = css.resolve`
  & {
    color: ${primatyColor};
  }
`;
```
but it throws with error `Error: Top-level selectors may not contain the parent selector "&"`
and stack trace:

```
Uncaught     at Object.wrapException (file:///project/node_modules/sass/sass.dart.js:6290:17)
    at SelectorList0.resolveParentSelectors$2$implicitParent (file:///project/node_modules/sass/sass.dart.js:83252:17)
    at _EvaluateVisitor_visitStyleRule_closure17.call$0 (file:///project/node_modules/sass/sass.dart.js:79693:17)
    at _EvaluateVisitor1._evaluate0$_addExceptionSpan$1$2 (file:///project/node_modules/sass/sass.dart.js:78710:23)
    at _EvaluateVisitor1._evaluate0$_addExceptionSpan$2 (file:///project/node_modules/sass/sass.dart.js:78731:19)
    at _EvaluateVisitor1.visitStyleRule$1 (file:///project/node_modules/sass/sass.dart.js:77828:33)
    at StyleRule0.accept$1$1 (file:///project/node_modules/sass/sass.dart.js:89894:22)
    at StyleRule0.accept$1 (file:///project/node_modules/sass/sass.dart.js:89897:19)
    at _EvaluateVisitor1.visitStylesheet$1 (file:///project/node_modules/sass/sass.dart.js:77311:16)
    at _EvaluateVisitor__execute_closure1.call$0 (file:///project/node_modules/sass/sass.dart.js:79085:10)
    at _EvaluateVisitor1._evaluate0$_withEnvironment$1$2 (file:///project/node_modules/sass/sass.dart.js:78517:25)
    at _EvaluateVisitor1._evaluate0$_withEnvironment$2 (file:///project/node_modules/sass/sass.dart.js:78522:19)
    at _EvaluateVisitor1._evaluate0$_execute$5$configuration$namesInErrors$nodeWithSpan (file:///project/node_modules/sass/sass.dart.js:77202:13)
    at _EvaluateVisitor1._evaluate0$_execute$2 (file:///project/node_modules/sass/sass.dart.js:77212:19)
    at _EvaluateVisitor_run_closure1.call$0 (file:///project/node_modules/sass/sass.dart.js:78977:67)
    at Object._rootRun (file:///project/node_modules/sass/sass.dart.js:12412:16)
    at processResult (file:///project/node_modules/next/dist/compiled/webpack/bundle5.js:62187:19)
    at <unknown> (file:///project/node_modules/next/dist/compiled/webpack/bundle5.js:62289:5)
    at <unknown> (file:///project/node_modules/next/dist/compiled/webpack/bundle5.js:27510:11)
    at <unknown> (file:///project/node_modules/next/dist/compiled/webpack/bundle5.js:27362:18)
    at context.callback (file:///project/node_modules/next/dist/compiled/webpack/bundle5.js:27235:13)
    at <unknown> (file:///project/node_modules/next/dist/build/webpack/loaders/babel-loader/src/index.js:4:106)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at runNextTicks (internal/process/task_queues.js:64:3)
    at processImmediate (internal/timers.js:437:9)
```

so the only workaround I found for this case is to use some root-level selector like `div` which results to `div.jsx-3079332898` selector in CSS

**Comment by SwiftWinds** [comment]
Hmm... I'm sorry this isn't terribly useful, @belkosyak, but you could always look into fixing it yourself and pull-requesting. I'm sorry, but I'm not the owner of this repo nor a very active contributor, so I'm not sure if I can dedicate any time to write a solution to the problem you mentioned. Sorry about that
